### ISSUE TITLE
RACER-ERROR: OWLAPI Runtime Error: Can't find ontology VOID (nRQL Error)

### ISSUE THREAD

**Issue by fcbr** [ha-mo-we/Racer#6]
I'm trying to load [SKOS](http://www.w3.org/2004/02/skos/vocabs) into Racer via OWL-READ-FILE, but I get back:

`RACER-ERROR: OWLAPI Runtime Error: Can't find ontology VOID (nRQL Error)`

This happens with both the open source version as well as the 2.0 version.

**Comment by fcbr** [comment]
Removing the `<owl:Ontology>...</owl:Ontology>` from the SKOS.rdf files makes Racer happy, BTW.

**Comment by ha-mo-we** [comment]
Dear Fabricio,

Thank you for pointing this out. I think I have fixed the problem. I need to test the solution thoroughly though, before uploading the patch.

Best regards,
Ralf

**Comment by ha-mo-we** [comment]
> On 08.08.2015, at 15:58, Fabricio Chalub notifications@github.com wrote:
> 
> Removing the owl:Ontology.../owl:Ontology from the SKOS.rdf files makes Racer happy, BTW.

The culprit are the annotations via rdfs:isDefinedBy .

**Comment by ha-mo-we** [comment]
Dear Fabricio,

Please check out Racer again. I hope the problem is solved now.

Thank you for your interest in Racer.

Best regards,
Ralf

> On 08.08.2015, at 15:58, Fabricio Chalub notifications@github.com wrote:
> 
> Removing the owl:Ontology.../owl:Ontology from the SKOS.rdf files makes Racer happy, BTW.
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/ha-mo-we/Racer/issues/6#issuecomment-128983191.

Prof. Dr. Ralf Möller 
Direktor des Instituts für Informationssysteme 

Universität zu Lübeck
Institut für Informationssysteme 

Tel +49 451 500 5700
Mobil +49 176 56946432
Fax +49 451 500 5702 
E-Mail moeller@uni-luebeck.de mailto:stelzner@ifis.uni-luebeck.de
www.ifis.uni-luebeck.de http://www.ifis.uni-luebeck.de/ 

Ratzeburger Allee 160 / Geb. 64
23562 Lübeck

**Comment by fcbr** [comment]
It works now.  I'll close this issue; thanks!
